runtime: nodejs24

entrypoint: node dist/src/main

env_variables:
  NODE_ENV: production

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 1
